const ActionType = {
    SET_NAME_USER: 'SET_NAME_USER',
    SET_TOKEN_USER: 'SET_TOKEN_USER',
    SET_EXPIRED_USER: 'SET_EXPIRED_USER',
    SET_PICTURE_USER: 'SET_PICTURE_USER',
    SET_ROLE_USER: 'SET_ROLE_USER',
    SET_TAHUN_AJAR: 'SET_TAHUN_AJAR'
}

export default ActionType